---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: What are Processes?
    - name: module-02
      label: Killing Processes
    - name: module-03
      label: What is a Service?
    - name: module-04
      label: Starting and Enabling a Service with systemctl
    - name: module-05
      label: Restarting a Service to Apply Configuration Changes
tabs:
  - name: ">_ root"
    port: 443
    path: /tty1
    user: root
    host: rhel
  - name: ">_ rhel"
    port: 443
    path: /tty2
    user: rhel
    host: rhel
