=== What is a Service?

The process you interacted with in the previous step was a foreground
process. It ran in a terminal window where you could see it. Some
processes run in the background, out of view of the user. These
background processes allow the system to carry out many operations in
parallel. Background processes that continuously carry out a set of
actions are called _services_.

_Daemons_ are even more specialized. These are services that and are
specifically designed to supervise or support other processes.
Typically, daemons are denoted by a *d* at the end of their name. For
example, *firewalld* is the daemon which handles firewall functionality.
These daemons lie in wait, listening for the user to issue a command to
tell them to change their behavior.

== Viewing the status of a service

** Podman is a daemonless, open source, Linux native tool 
designed to make it easy to find, run, build, share and deploy applications 
using Open Containers Initiative (OCI) Containers and Container Images. 

Check the status of the *podman* service with the
following command:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
systemctl status podman.service --no-pager
----

.Output
[source,text]
----
● podman.service - Podman API Service
     Loaded: loaded (/usr/lib/systemd/system/podman.service; disabled; preset: disabled)
     Active: inactive (dead)
TriggeredBy: ○ podman.socket
       Docs: man:podman-system-service(1)

<< OUTPUT ABRIDGED >>
----

From this status message it is clear that the *podman* service is
installed but inactive and disabled. 

But what is managing this service? It turns out
that another service, *systemd*, is in charge of managing all of the
services on the system.

== *systemd* vs. *systemctl*

When researching service management, you will come across two very
similar terms: *systemd* and *systemctl*. These are very closely
related. *systemd*, short for system daemon, manages the state of the
system and any services running on it. Since *systemd* is a daemon, it
runs in the background and needs a set of commands for users to interact
with it. *systemctl* provides these commands. The `+systemctl status+`
command above is one example of this, and the upcoming steps will walk
you through starting and enabling a service with *systemctl*.
