=== Starting and Enabling a Service with systemctl

For this example, you will be using the Network File System (NFS)
service. This service allows users on client systems to view files and
directories over a network as if they were on the client’s local drive.
Rather than focusing on the functionality of this service, though, this
lab simply uses it as an example of how to start a service and implement
configuration file changes.

To begin, run the command to show the export list for the NFS server:

NOTE: The below command is expected to fail and may take some time to complete.

[source,bash,subs="+macros,+attributes",role=execute]
----
showmount -e
----

This throws an error, because the NFS service is not running.

[source,text]
----
clnt_create: RPC: Program not registered
----

To solve this issue, you need to start the service. However, if you want
the service to start each time you boot the system, you need to enable
the service. You can do both of these operations in one line:

[source,bash,subs="+macros,+attributes",role=execute]
----
systemctl enable --now nfs-server
----

[source,text]
----
Created symlink /etc/systemd/system/multi-user.target.wants/nfs-server.service → /usr/lib/systemd/system/nfs-server.service
----

NOTE: If you just wanted to start a service, `+systemctl start+`
followed by the service name will do the trick. However, the service
will not start again if you reboot the system.

Now the *nfs-server* service is started, and it will start every time
the system starts as well. Run the `+showmount+` command again now that
the service is active:

[source,bash,subs="+macros,+attributes",role=execute]
----
showmount -e
----

[source,text,subs="+macros,+attributes"]
----
Export list for bastion.{{ guid }}.internal:
----

The export list is currently blank, which is something controlled by a
configuration file. You may assume that changing a config file would
immediately lead to changes in the service, but this is not the case.
The next step will walk you through restarting a service to reload
configuration files.
